global:
  scrape_interval: 30s
  evaluation_interval: 30s

#rule_files:

scrape_configs:
  - job_name: 'prometheus_metrics'
    scrape_interval: 30s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'mic-code'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'service'
